"use client";import {useState} from "react";import SiteNav from "../SiteNav";import {glossary} from "../../lib/poker";
const rules=[
 {title:"下注尺寸",lead:"2BB / 2.5BB / 3BB 是金额，不是 Bet 层级。",body:"BB 是大盲注单位。如果盲注是 10/20，1BB=20，2.5BB=50，3BB=60。Open to 2.5BB 就是把总下注额加到 2.5 个大盲。"},
 {title:"Bet 层级",lead:"3-Bet 不是“加到三倍”。",body:"盲注是第一层投入，Open Raise 是第二层，再次加注叫 3-Bet；面对 3-Bet 再次加注叫 4-Bet。比如 BTN 2.5BB open，BB 加到 10BB，仍然叫 3-Bet。"},
 {title:"6-max 位置",lead:"UTG → HJ → CO → BTN → SB → BB。",body:"位置越靠后，通常越容易使用更宽的 RFI Range。Hero 在 PokerSight 牌桌中固定在下方，其他位置围绕 Hero 旋转。"},
 {title:"RFI",lead:"前面没人入池时，你第一个加注。",body:"Raise First In。当前 RFI Range 模式用于学习不同位置在 folded-to-you 场景下的开池范围。"},
 {title:"Defense",lead:"面对别人已经开池后，你如何继续。",body:"Defense 取决于 Hero 位置、对手位置、open size、stack depth 和 rake。BTN→BB 只是第一种场景，后续还会有 CO→BB、SB→BB、UTG→BB 等。"},
 {title:"有效筹码",lead:"真正决定可投入深度的是较短一方筹码。",body:"如果你有 100BB、对手只有 40BB，这手牌的有效筹码是 40BB。很多 preflop 和 postflop 策略都会随有效筹码变化。"}
];
export default function Learn(){const [term,setTerm]=useState<string|null>(null);return <main><SiteNav/><section className="pageHead"><div><p className="eyebrow">POKER BASICS</p><h1>术语与规则</h1><p>先分清“下注金额”和“下注层级”，再理解位置、Range 与 Defense。</p></div></section><section className="ruleGrid">{rules.map(r=><article className="ruleCard" key={r.title}><small>RULE</small><h2>{r.title}</h2><strong>{r.lead}</strong><p>{r.body}</p></article>)}</section><section className="learnDivider"><span>术语库 · A–Z</span></section><section className="glossaryList">{Object.entries(glossary).sort(([a],[b])=>a.localeCompare(b,"en",{sensitivity:"base",numeric:true})).map(([k,v])=><button className="conceptRow" key={k} onClick={()=>setTerm(k)}><b>{k}</b><span>{v.zh}</span><p>{v.short}</p><em>查看详情 →</em></button>)}</section>{term&&glossary[term]&&<div className="overlay" onClick={()=>setTerm(null)}><article onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setTerm(null)}>×</button><p className="eyebrow">POKER TERM</p><h2>{term} · {glossary[term].zh}</h2><strong>{glossary[term].short}</strong><p>{glossary[term].detail}</p><button className="next" onClick={()=>setTerm(null)}>知道了</button></article></div>}</main>}