import Link from "next/link";import SiteNav from "./SiteNav";
const seats=[
  {pos:"UTG",name:"Player 1",stack:"100 BB",action:"Fold",cls:"seat-utg"},
  {pos:"HJ",name:"Player 2",stack:"98 BB",action:"Open 2.5BB",cls:"seat-hj"},
  {pos:"CO",name:"Player 3",stack:"104 BB",action:"Fold",cls:"seat-co"},
  {pos:"BTN",name:"Player 4",stack:"100 BB",action:"Dealer",cls:"seat-btn",dealer:true},
  {pos:"SB",name:"Player 5",stack:"99.5 BB",action:"0.5 BB",cls:"seat-sb",blind:true},
  {pos:"BB",name:"You",stack:"99 BB",action:"1 BB",cls:"seat-bb hero",blind:true}
];
export default function Home(){return <main><SiteNav/><section className="dashboardHero"><p className="eyebrow">POKER STUDY SYSTEM</p><h1>练决策，记范围，<br/>理解每一步为什么。</h1><p>把训练、169 起手牌矩阵和术语学习拆成独立工作区，避免长页面来回翻找。</p></section><section className="homeTableSection"><div className="homeTableCopy"><p className="eyebrow">6-MAX POSITION MAP</p><h2>先建立位置感，再学习范围。</h2><p>标准 6-max：UTG → HJ → CO → BTN → SB → BB。位置会直接影响开池范围、跟注范围和整体策略。</p><Link href="/trainer" className="tableCta">进入训练 →</Link></div><div className="pokerStage"><div className="pokerRail"><div className="pokerFelt"><div className="feltMark">POKERSIGHT</div><div className="potDisplay"><small>POT</small><strong>4 BB</strong><span>Preflop</span></div><div className="boardGhost"><i/><i/><i/><i/><i/></div></div></div>{seats.map(s=><Link href="/learn" key={s.pos} className={"tableSeat "+s.cls}><div className="avatar">{s.pos==="BB"?"YOU":s.pos}</div><div className="seatMeta"><div className="seatLine"><strong>{s.pos}</strong>{s.dealer&&<span className="dealerChip">D</span>}{s.blind&&<span className="blindChip">{s.pos}</span>}</div><span>{s.name}</span><small>{s.stack}</small></div><em className={"actionTag "+(s.action.includes("Open")?"active":"")}>{s.action}</em></Link>)}</div></section><section className="workspaceGrid"><Link href="/trainer" className="workspaceCard primary"><small>01 · TRAINER</small><h2>开始训练</h2><p>从 Preflop 决策题开始，做完立即得到解释与复习提示。</p><span>进入训练 →</span></Link><Link href="/matrix" className="workspaceCard"><small>02 · MATRIX</small><h2>169 起手牌矩阵</h2><p>整张表独立展示，反复查看 suited / offsuit / pair 的结构和牌型强弱。</p><span>打开矩阵 →</span></Link><Link href="/learn" className="workspaceCard"><small>03 · LEARN</small><h2>扑克术语</h2><p>集中查看 BTN、UTG、3-Bet、Range、Equity 等基础概念。</p><span>开始学习 →</span></Link></section><section className="statusStrip"><div><b>当前阶段</b><span>M1 · Preflop Foundation</span></div><div><b>下一阶段</b><span>Position Range + Equity</span></div><div><b>模式</b><span>Study only</span></div></section></main>}